/**
 * Static surah metadata (number, English name, ayah count). Used by
 * GET /api/quran/surahs and by the seed script to know how many chapters to
 * fetch. Lets the surah list work even before quran_verses is seeded.
 */
export interface SurahMeta {
  surah_number: number;
  name: string;
  ayah_count: number;
}

export const SURAHS: SurahMeta[] = [
  { surah_number: 1, name: "Al-Fatihah", ayah_count: 7 },
  { surah_number: 2, name: "Al-Baqarah", ayah_count: 286 },
  { surah_number: 3, name: "Aal-E-Imran", ayah_count: 200 },
  { surah_number: 4, name: "An-Nisa", ayah_count: 176 },
  { surah_number: 5, name: "Al-Ma'idah", ayah_count: 120 },
  { surah_number: 6, name: "Al-An'am", ayah_count: 165 },
  { surah_number: 7, name: "Al-A'raf", ayah_count: 206 },
  { surah_number: 8, name: "Al-Anfal", ayah_count: 75 },
  { surah_number: 9, name: "At-Tawbah", ayah_count: 129 },
  { surah_number: 10, name: "Yunus", ayah_count: 109 },
  { surah_number: 11, name: "Hud", ayah_count: 123 },
  { surah_number: 12, name: "Yusuf", ayah_count: 111 },
  { surah_number: 13, name: "Ar-Ra'd", ayah_count: 43 },
  { surah_number: 14, name: "Ibrahim", ayah_count: 52 },
  { surah_number: 15, name: "Al-Hijr", ayah_count: 99 },
  { surah_number: 16, name: "An-Nahl", ayah_count: 128 },
  { surah_number: 17, name: "Al-Isra", ayah_count: 111 },
  { surah_number: 18, name: "Al-Kahf", ayah_count: 110 },
  { surah_number: 19, name: "Maryam", ayah_count: 98 },
  { surah_number: 20, name: "Taha", ayah_count: 135 },
  { surah_number: 21, name: "Al-Anbya", ayah_count: 112 },
  { surah_number: 22, name: "Al-Hajj", ayah_count: 78 },
  { surah_number: 23, name: "Al-Mu'minun", ayah_count: 118 },
  { surah_number: 24, name: "An-Nur", ayah_count: 64 },
  { surah_number: 25, name: "Al-Furqan", ayah_count: 77 },
  { surah_number: 26, name: "Ash-Shu'ara", ayah_count: 227 },
  { surah_number: 27, name: "An-Naml", ayah_count: 93 },
  { surah_number: 28, name: "Al-Qasas", ayah_count: 88 },
  { surah_number: 29, name: "Al-Ankabut", ayah_count: 69 },
  { surah_number: 30, name: "Ar-Rum", ayah_count: 60 },
  { surah_number: 31, name: "Luqman", ayah_count: 34 },
  { surah_number: 32, name: "As-Sajdah", ayah_count: 30 },
  { surah_number: 33, name: "Al-Ahzab", ayah_count: 73 },
  { surah_number: 34, name: "Saba", ayah_count: 54 },
  { surah_number: 35, name: "Fatir", ayah_count: 45 },
  { surah_number: 36, name: "Ya-Sin", ayah_count: 83 },
  { surah_number: 37, name: "As-Saffat", ayah_count: 182 },
  { surah_number: 38, name: "Sad", ayah_count: 88 },
  { surah_number: 39, name: "Az-Zumar", ayah_count: 75 },
  { surah_number: 40, name: "Ghafir", ayah_count: 85 },
  { surah_number: 41, name: "Fussilat", ayah_count: 54 },
  { surah_number: 42, name: "Ash-Shura", ayah_count: 53 },
  { surah_number: 43, name: "Az-Zukhruf", ayah_count: 89 },
  { surah_number: 44, name: "Ad-Dukhan", ayah_count: 59 },
  { surah_number: 45, name: "Al-Jathiyah", ayah_count: 37 },
  { surah_number: 46, name: "Al-Ahqaf", ayah_count: 35 },
  { surah_number: 47, name: "Muhammad", ayah_count: 38 },
  { surah_number: 48, name: "Al-Fath", ayah_count: 29 },
  { surah_number: 49, name: "Al-Hujurat", ayah_count: 18 },
  { surah_number: 50, name: "Qaf", ayah_count: 45 },
  { surah_number: 51, name: "Adh-Dhariyat", ayah_count: 60 },
  { surah_number: 52, name: "At-Tur", ayah_count: 49 },
  { surah_number: 53, name: "An-Najm", ayah_count: 62 },
  { surah_number: 54, name: "Al-Qamar", ayah_count: 55 },
  { surah_number: 55, name: "Ar-Rahman", ayah_count: 78 },
  { surah_number: 56, name: "Al-Waqi'ah", ayah_count: 96 },
  { surah_number: 57, name: "Al-Hadid", ayah_count: 29 },
  { surah_number: 58, name: "Al-Mujadila", ayah_count: 22 },
  { surah_number: 59, name: "Al-Hashr", ayah_count: 24 },
  { surah_number: 60, name: "Al-Mumtahanah", ayah_count: 13 },
  { surah_number: 61, name: "As-Saff", ayah_count: 14 },
  { surah_number: 62, name: "Al-Jumu'ah", ayah_count: 11 },
  { surah_number: 63, name: "Al-Munafiqun", ayah_count: 11 },
  { surah_number: 64, name: "At-Taghabun", ayah_count: 18 },
  { surah_number: 65, name: "At-Talaq", ayah_count: 12 },
  { surah_number: 66, name: "At-Tahrim", ayah_count: 12 },
  { surah_number: 67, name: "Al-Mulk", ayah_count: 30 },
  { surah_number: 68, name: "Al-Qalam", ayah_count: 52 },
  { surah_number: 69, name: "Al-Haqqah", ayah_count: 52 },
  { surah_number: 70, name: "Al-Ma'arij", ayah_count: 44 },
  { surah_number: 71, name: "Nuh", ayah_count: 28 },
  { surah_number: 72, name: "Al-Jinn", ayah_count: 28 },
  { surah_number: 73, name: "Al-Muzzammil", ayah_count: 20 },
  { surah_number: 74, name: "Al-Muddaththir", ayah_count: 56 },
  { surah_number: 75, name: "Al-Qiyamah", ayah_count: 40 },
  { surah_number: 76, name: "Al-Insan", ayah_count: 31 },
  { surah_number: 77, name: "Al-Mursalat", ayah_count: 50 },
  { surah_number: 78, name: "An-Naba", ayah_count: 40 },
  { surah_number: 79, name: "An-Nazi'at", ayah_count: 46 },
  { surah_number: 80, name: "Abasa", ayah_count: 42 },
  { surah_number: 81, name: "At-Takwir", ayah_count: 29 },
  { surah_number: 82, name: "Al-Infitar", ayah_count: 19 },
  { surah_number: 83, name: "Al-Mutaffifin", ayah_count: 36 },
  { surah_number: 84, name: "Al-Inshiqaq", ayah_count: 25 },
  { surah_number: 85, name: "Al-Buruj", ayah_count: 22 },
  { surah_number: 86, name: "At-Tariq", ayah_count: 17 },
  { surah_number: 87, name: "Al-A'la", ayah_count: 19 },
  { surah_number: 88, name: "Al-Ghashiyah", ayah_count: 26 },
  { surah_number: 89, name: "Al-Fajr", ayah_count: 30 },
  { surah_number: 90, name: "Al-Balad", ayah_count: 20 },
  { surah_number: 91, name: "Ash-Shams", ayah_count: 15 },
  { surah_number: 92, name: "Al-Layl", ayah_count: 21 },
  { surah_number: 93, name: "Ad-Duha", ayah_count: 11 },
  { surah_number: 94, name: "Ash-Sharh", ayah_count: 8 },
  { surah_number: 95, name: "At-Tin", ayah_count: 8 },
  { surah_number: 96, name: "Al-Alaq", ayah_count: 19 },
  { surah_number: 97, name: "Al-Qadr", ayah_count: 5 },
  { surah_number: 98, name: "Al-Bayyinah", ayah_count: 8 },
  { surah_number: 99, name: "Az-Zalzalah", ayah_count: 8 },
  { surah_number: 100, name: "Al-Adiyat", ayah_count: 11 },
  { surah_number: 101, name: "Al-Qari'ah", ayah_count: 11 },
  { surah_number: 102, name: "At-Takathur", ayah_count: 8 },
  { surah_number: 103, name: "Al-Asr", ayah_count: 3 },
  { surah_number: 104, name: "Al-Humazah", ayah_count: 9 },
  { surah_number: 105, name: "Al-Fil", ayah_count: 5 },
  { surah_number: 106, name: "Quraysh", ayah_count: 4 },
  { surah_number: 107, name: "Al-Ma'un", ayah_count: 7 },
  { surah_number: 108, name: "Al-Kawthar", ayah_count: 3 },
  { surah_number: 109, name: "Al-Kafirun", ayah_count: 6 },
  { surah_number: 110, name: "An-Nasr", ayah_count: 3 },
  { surah_number: 111, name: "Al-Masad", ayah_count: 5 },
  { surah_number: 112, name: "Al-Ikhlas", ayah_count: 4 },
  { surah_number: 113, name: "Al-Falaq", ayah_count: 5 },
  { surah_number: 114, name: "An-Nas", ayah_count: 6 },
];

export const TOTAL_SURAHS = SURAHS.length; // 114
